### ISSUE TITLE
libmkl_rt.dylib not found

### ISSUE THREAD

**Issue by cuckootan** [bytedeco/javacpp#262]
Hi, I encounter a problem when I use [Nd4j](https://github.com/deeplearning4j/nd4j).

Platform: macos
javacpp: 1.4.2
mkl-platform: 2018.3-1.4.2

I execute cmd: `otool -L ${JAVACPP_CACHE_PATH}/libjnimkl_rt.dylib`, the result is as follows:

```
libjnimkl_rt.dylib:
	libjnimkl_rt.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libmkl_rt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/JavaVM.framework/Versions/A/JavaVM (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
```

It seems that libjnimkl_rt.dylib refereces libmkl_rt.dylib, but libmkl_rt.dylib not found. How to fix it?

**Comment by saudet** [comment]
That has been fixed, please use ND4J 1.0.0-beta2.

**Comment by cuckootan** [comment]
> That has been fixed, please use ND4J 1.0.0-beta2.

Sorry to forget to describe the nd4j version. Actually, the nd4j version I used is exactly 1.0.0-beta2. Here is my pom:

```
<dependency>
            <groupId>org.nd4j</groupId>
            <!--<artifactId>nd4j-native</artifactId>-->
            <artifactId>nd4j-native-platform</artifactId>
            <version>1.0.0-beta2</version>
            <!--<version>0.9.1</version>-->
 </dependency>
```

**Comment by cuckootan** [comment]
> You're using an old buggy version of Spring.
> That could be the cause of the error,
> see [deeplearning4j/deeplearning4j#6132](https://github.com/deeplearning4j/deeplearning4j/issues/6132)

Well, after I set spring-boot version to 2.0.5.RELEASE, the problem still exists.

**Comment by saudet** [comment]
Could you provide a code snippet to reproduce this issue?

**Comment by cuckootan** [comment]
> Could you provide a code snippet to reproduce this issue?

```
public static void main(String[] args) {

        Nd4j.setDataType(DataBuffer.Type.DOUBLE);

        INDArray a = Nd4j.create(new double[]{1, 3, 5, 9}, new int[]{4});
        INDArray b = Nd4j.create(new double[]{2, 3, 1, 2}, new int[]{4});
        INDArray c = a.mmul(b.transpose());
        System.out.println(c.getDouble(0));

        INDArray sa = Nd4j.createSparseCSR(new double[]{1.2, 2.4, 1.5}, new int[]{1, 3, 5}, new int[]{0}, new int[]{2}, new long[]{7});
        INDArray sb = Nd4j.create(new double[]{1, 1, 1, 1, 1, 1, 1}, new long[]{7});
        System.out.println(sb.mmul(sa));
    }
```

**Comment by saudet** [comment]
Ah, I see, you're using sparse matrices. That requires the full version of MKL, but we can't bundle it because its license forbids it. You'll need to install it separately to get that working:
https://software.intel.com/en-us/mkl

**Comment by cuckootan** [comment]
> Ah, I see, you're using sparse matrices. That requires the full version of MKL, but we can't bundle it because its license forbids it. You'll need to install it separately to get that working:
> https://software.intel.com/en-us/mkl

Ok, got it. Thanks! I'll try it.
