### ISSUE TITLE
Parser NPE

### ISSUE THREAD

**Issue by jpsacha** [bytedeco/javacpp#30]
I am trying to create a new preset for Basler Pylon librarty. No files gets generated, only getting an error:

```
...
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to execute JavaCPP Builder
        at org.bytedeco.javacpp.tools.BuildMojo.execute(BuildMojo.java:276)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.NullPointerException
        at org.bytedeco.javacpp.tools.Parser.function(Parser.java:1191)
        at org.bytedeco.javacpp.tools.Parser.declarations(Parser.java:2285)
        at org.bytedeco.javacpp.tools.Parser.group(Parser.java:1926)
        at org.bytedeco.javacpp.tools.Parser.declarations(Parser.java:2284)
        at org.bytedeco.javacpp.tools.Parser.namespace(Parser.java:2193)
        at org.bytedeco.javacpp.tools.Parser.declarations(Parser.java:2283)
        at org.bytedeco.javacpp.tools.Parser.parse(Parser.java:2359)
        at org.bytedeco.javacpp.tools.Parser.parse(Parser.java:2454)
        at org.bytedeco.javacpp.tools.Builder.parse(Builder.java:66)
        at org.bytedeco.javacpp.tools.Builder.build(Builder.java:623)
        at org.bytedeco.javacpp.tools.BuildMojo.execute(BuildMojo.java:269)
        ... 21 more
```

**Comment by saudet** [comment]
Looks like params is null when it shouldn't. We should add a null check
there, to skip that block, and get more meaningful info about the parsing
error...

**Comment by saudet** [comment]
I've fixed the `NullPointerException` in the latest commit, so let me know if you get some more verbose error with that. Thanks for reporting!

**Comment by jpsacha** [comment]
I am still getting NPE, with a different stack trace this time:

```
Caused by: java.lang.NullPointerException
        at org.bytedeco.javacpp.tools.Parser.function(Parser.java:1273)
        at org.bytedeco.javacpp.tools.Parser.declarations(Parser.java:2283)
        at org.bytedeco.javacpp.tools.Parser.group(Parser.java:1923)
        at org.bytedeco.javacpp.tools.Parser.declarations(Parser.java:2282)
        at org.bytedeco.javacpp.tools.Parser.namespace(Parser.java:2191)
        at org.bytedeco.javacpp.tools.Parser.declarations(Parser.java:2281)
        at org.bytedeco.javacpp.tools.Parser.parse(Parser.java:2357)
        at org.bytedeco.javacpp.tools.Parser.parse(Parser.java:2452)
        at org.bytedeco.javacpp.tools.Builder.parse(Builder.java:66)
        at org.bytedeco.javacpp.tools.Builder.build(Builder.java:623)
        at org.bytedeco.javacpp.tools.BuildMojo.execute(BuildMojo.java:269)
        ... 21 more
```

Looks that the line with NPE:

```java
dcl.signature = dcl.javaName + params.signature;
```

possibly `params` is `null`.

**Comment by jpsacha** [comment]
The last commit (5c259e1) fixed the issue. Thanks.
