### ISSUE TITLE
Function pointer type in C did not get translated well

### ISSUE THREAD

**Issue by lancewoo** [bytedeco/javacpp#580]
I used some function pointer definition from a C library in a C++code context. When it gets translated, the build did not pass.
Check the failed message:

 ```
Build multiple targets stcrpc_armeabi-v7a ShotSync_armeabi-v7a
ninja: Entering directory `E:\work\projects\rpcjni\shotsync\.cxx\cmake\debug\armeabi-v7a'
[1/3] Building CXX object CMakeFiles/ShotSync.dir/ShotSync.cpp.o
FAILED: CMakeFiles/ShotSync.dir/ShotSync.cpp.o 
D:\Android\AndroidSdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi19 --gcc-toolchain=D:/Android/AndroidSdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=D:/Android/AndroidSdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot  -DShotSync_EXPORTS -IE:/work/projects/rpcjni/shotsync/src/main/cpp/libstc-rpc/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security  -std=c++11 -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/ShotSync.dir/ShotSync.cpp.o -MF CMakeFiles\ShotSync.dir\ShotSync.cpp.o.d -o CMakeFiles/ShotSync.dir/ShotSync.cpp.o -c E:/work/projects/rpcjni/shotsync/src/main/cpp/ShotSync.cpp
E:/work/projects/rpcjni/shotsync/src/main/cpp/ShotSync.cpp:1193:41: error: no viable conversion from 'JavaCPP_com_senter_shotsync_ShotSync_00024rpc_1handler_1t' to 'rpc_handler_t' (aka 'int (*)(rpc_request_hdr_t *, rpc_reply_t *)')
        client::ClientSetMessageHandler(*ptr0);
                                        ^~~~~
E:/work/projects/rpcjni/shotsync/src/main/cpp/RpcImpl.h:11:48: note: passing argument to parameter 'userHandler' here
    void ClientSetMessageHandler(rpc_handler_t userHandler);
                                               ^
1 error generated.
[2/3] Building CXX object CMakeFiles/ShotSync.dir/jnijavacpp.cpp.o
ninja: build stopped: subcommand failed.
```

Check this code and its repository for the scenario.
[rpc_handler_t ](https://github.com/lancewoo/rpcjni/blob/95eeea02affd9d1d35d6555c270c0412cb2c1554/shotsync/src/main/cpp/RpcImpl.h#L11)

And the mapper Java: [NativeLibraryConfig.java](https://github.com/lancewoo/rpcjni/blob/95eeea02affd9d1d35d6555c270c0412cb2c1554/shotsync/src/main/java/com/senter/shotsync/NativeLibraryConfig.java)

Any suggestions?

**Comment by saudet** [comment]
What does `ShotSync.java` looks like?

**Comment by lancewoo** [comment]
It's here like: 
[ @Namespace("client") public static native void ClientSetMessageHandler(@ByVal rpc_handler_t userHandler);](https://github.com/lancewoo/rpcjni/blob/d0680add3bfeae07a6f794e6e2700aa89a22f96a/shotsync/src/main/java/com/senter/shotsync/ShotSync.java#L21)

**Comment by saudet** [comment]
The `@ByVal` annotation is what is causing problems here, it shouldn't be there. Could you let me know how you're getting this?

**Comment by lancewoo** [comment]
I created this repo [rpc-jni](https://github.com/lancewoo/rpcjni) just to reproduce this problem. It's an Android Studio project.

Besides, in my project I created a header file to redefine the structs and that function pointer to make it build successfully, and skipped stc_rpc.h. It works well.

This is my definition.
```
typedef struct rpc_request_hdr_t__ {
    unsigned code;
    char buffer[RPC_PAYLOAD_MAX];
} __attribute__((packed)) RpcRequestHdr;

typedef struct rpc_reply_t__ {
    unsigned code;
    char buffer[RPC_PAYLOAD_MAX];
} __attribute__((packed)) RpcReply;

typedef int (*RpcHandler)(RpcRequestHdr *request, RpcReply *reply);
```

**Comment by saudet** [comment]
I see, the include order of the header files is incorrect. "cinclude" and "include" weren't designed to be used together. What happens if you do something like this?
```java
@Properties(
        value = @Platform(
                include = {
                        "stc_rpc.h",
                        "RpcImpl.h"
                },
                library = "ShotSync"),
        target = "com.senter.shotsync.ShotSync"
)
```

**Comment by lancewoo** [comment]
It will result in the following link error because the C library header does not have extern "C":

```
Build command failed.
Error while executing process D:\Android\AndroidSdk\cmake\3.10.2.4988404\bin\ninja.exe with arguments {-C E:\work\projects\rpcjni\shotsync\.cxx\cmake\debug\armeabi-v7a ShotSync stcrpc}
ninja: Entering directory `E:\work\projects\rpcjni\shotsync\.cxx\cmake\debug\armeabi-v7a'
[1/3] Building CXX object CMakeFiles/ShotSync.dir/ShotSync.cpp.o
[2/3] Building CXX object CMakeFiles/ShotSync.dir/jnijavacpp.cpp.o
[3/3] Linking CXX shared library E:\work\projects\rpcjni\shotsync\build\intermediates\cmake\debug\obj\armeabi-v7a\libShotSync.so
FAILED: E:/work/projects/rpcjni/shotsync/build/intermediates/cmake/debug/obj/armeabi-v7a/libShotSync.so 
cmd.exe /C "cd . && D:\Android\AndroidSdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi19 --gcc-toolchain=D:/Android/AndroidSdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=D:/Android/AndroidSdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security  -std=c++11 -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libShotSync.so -o E:\work\projects\rpcjni\shotsync\build\intermediates\cmake\debug\obj\armeabi-v7a\libShotSync.so CMakeFiles/ShotSync.dir/RpcImpl.cpp.o CMakeFiles/ShotSync.dir/ShotSync.cpp.o CMakeFiles/ShotSync.dir/jnijavacpp.cpp.o  E:/work/projects/rpcjni/shotsync/build/intermediates/cmake/debug/obj/armeabi-v7a/libstcrpc.so -llog -latomic -lm && cd ."
ld: error: undefined symbol: rpc_stop(rpc*)
>>> referenced by ShotSync.cpp:1185 (E:/work/projects/rpcjni/shotsync/src/main/cpp\ShotSync.cpp:1185)
>>>               CMakeFiles/ShotSync.dir/ShotSync.cpp.o:(Java_com_senter_shotsync_ShotSync_rpc_1stop)
>>> did you mean: extern "C" rpc_stop
>>> defined in: E:/work/projects/rpcjni/shotsync/build/intermediates/cmake/debug/obj/armeabi-v7a/libstcrpc.so

ld: error: undefined symbol: rpc_start(rpc*)
>>> referenced by ShotSync.cpp:1201 (E:/work/projects/rpcjni/shotsync/src/main/cpp\ShotSync.cpp:1201)
>>>               CMakeFiles/ShotSync.dir/ShotSync.cpp.o:(Java_com_senter_shotsync_ShotSync_rpc_1start)
>>> did you mean: extern "C" rpc_start
>>> defined in: E:/work/projects/rpcjni/shotsync/build/intermediates/cmake/debug/obj/armeabi-v7a/libstcrpc.so

ld: error: undefined symbol: rpc_call_noreply(rpc*, rpc_request_t*)
>>> referenced by ShotSync.cpp:1220 (E:/work/projects/rpcjni/shotsync/src/main/cpp\ShotSync.cpp:1220)
>>>               CMakeFiles/ShotSync.dir/ShotSync.cpp.o:(Java_com_senter_shotsync_ShotSync_rpc_1call_1noreply)

ld: error: undefined symbol: rpc_call(rpc*, rpc_request_t*)
>>> referenced by ShotSync.cpp:1239 (E:/work/projects/rpcjni/shotsync/src/main/cpp\ShotSync.cpp:1239)
>>>               CMakeFiles/ShotSync.dir/ShotSync.cpp.o:(Java_com_senter_shotsync_ShotSync_rpc_1call)

ld: error: undefined symbol: rpc_free(rpc*)
>>> referenced by ShotSync.cpp:1254 (E:/work/projects/rpcjni/shotsync/src/main/cpp\ShotSync.cpp:1254)
>>>               CMakeFiles/ShotSync.dir/ShotSync.cpp.o:(Java_com_senter_shotsync_ShotSync_rpc_1free)

ld: error: undefined symbol: rpc_init(int, int (*)(rpc_request_hdr_t*, rpc_reply_t*), rpc*)
>>> referenced by ShotSync.cpp:1271 (E:/work/projects/rpcjni/shotsync/src/main/cpp\ShotSync.cpp:1271)
>>>               CMakeFiles/ShotSync.dir/ShotSync.cpp.o:(Java_com_senter_shotsync_ShotSync_rpc_1init)

ld: error: undefined symbol: rpc_alloc()
>>> referenced by ShotSync.cpp:1287 (E:/work/projects/rpcjni/shotsync/src/main/cpp\ShotSync.cpp:1287)
>>>               CMakeFiles/ShotSync.dir/ShotSync.cpp.o:(Java_com_senter_shotsync_ShotSync_rpc_1alloc)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.



```

**Comment by lancewoo** [comment]
> 

If I put the header files both in the  ["cinclude"](https://github.com/lancewoo/rpcjni/blob/cfff6cba416548b5528211cbd21851dc660771bc/shotsync/src/main/java/com/senter/shotsync/NativeLibraryConfig.java#L14) block, it builds OK.
```
@Properties(
        value = @Platform(
                cinclude = {
                        "stc_rpc.h",
                        "RpcImpl.h"
                },
                library = "ShotSync"),
        target = "com.senter.shotsync.ShotSync"
)
```

**Comment by saudet** [comment]
I see, I think it makes sense to include always C header files before C++ header files, because we can call C functions from C++, but not the other way around, so I've pushed a fix for that in commit https://github.com/bytedeco/javacpp/commit/e79ebd5ff5fd6e7cd6c9f29173c2ffdc362c9832. Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by lancewoo** [comment]
Still failed for the same reason.
Do we have to trigger a new build for plugin gradle-javacpp-build? 
```
plugins {
    id 'com.android.library'
    id 'org.bytedeco.gradle-javacpp-build' version '1.5.7'
}

..........

dependencies {

    implementation 'org.bytedeco:javacpp:1.5.8-SNAPSHOT'

}
```

It seems there is no build today:
[https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/gradle-javacpp-build/](https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/gradle-javacpp-build/)

**Comment by lancewoo** [comment]
Verified. It's Okay now to mix use the _**cinclude**_ and **_include_**.
I cheated on Android Studio by replacing the cached javacpp-1.5.7.jar with downloaded javacpp-1.5.8-SNAPSHOT.jar, forcibly.
It builds well now.

Thanks！

**Comment by saudet** [comment]
The fix for this has been release with JavaCPP 1.5.8. Thanks for reporting and enjoy!

**Comment by lancewoo** [comment]
Great job! Thanks!
